package tsmux

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"tailscale.com/ipn"
	"tailscale.com/tailcfg"
)

// PAC renders a proxy auto-config that sends each tailnet's names to that
// profile's own proxy port. Browsers then reach every tailnet at once, with
// no system-wide interception of ordinary traffic.
func (c *Config) PAC() string {
	c.mu.RLock()
	defer c.mu.RUnlock()
	var b strings.Builder
	b.WriteString("// generated by tsmux -- do not edit\nfunction FindProxyForURL(url, host) {\n")
	b.WriteString("  host = host.toLowerCase();\n")
	b.WriteString("  if (host === \"localhost\" || shExpMatch(host, \"127.*\") || shExpMatch(host, \"*.local\")) return \"DIRECT\";\n")
	// PAC files are real JavaScript, so test for a literal address directly
	// rather than letting isInNet() trigger a DNS lookup on every domain.
	b.WriteString("  var tsmuxIsIP = /^[0-9]{1,3}(\\.[0-9]{1,3}){3}$/.test(host);\n")

	for _, p := range c.Ordered() {
		proxy := fmt.Sprintf("PROXY 127.0.0.1:%d; SOCKS5 127.0.0.1:%d", p.HTTPPort, p.SOCKSPort)
		for _, s := range p.Suffixes {
			apex := strings.TrimPrefix(s, ".")
			b.WriteString(fmt.Sprintf("  if (dnsDomainIs(host, %q) || host === %q) return %q; // %s\n",
				s, apex, proxy, p.Name))
		}
		for _, r := range p.IPRoutes {
			if ip, mask, ok := cidrToPAC(r); ok {
				b.WriteString(fmt.Sprintf("  if (tsmuxIsIP && isInNet(host, %q, %q)) return %q; // %s\n", ip, mask, proxy, p.Name))
			}
		}
		if p.MatchRoot {
			b.WriteString(fmt.Sprintf("  if (isPlainHostName(host)) return %q; // %s match_root\n", proxy, p.Name))
		}
	}
	b.WriteString("  return \"DIRECT\";\n}\n")
	return b.String()
}

func cidrToPAC(cidr string) (ip, mask string, ok bool) {
	_, n, err := net.ParseCIDR(cidr)
	if err != nil || n.IP.To4() == nil {
		return "", "", false
	}
	m := n.Mask
	return n.IP.String(), fmt.Sprintf("%d.%d.%d.%d", m[0], m[1], m[2], m[3]), true
}

func (c *Config) PACURL() string { return "http://" + c.Router.PACListen + "/proxy.pac" }

// StatusURL is the running daemon's JSON status. Clients (the menu bar app,
// `tsmux status`) read it instead of starting their own tsnet nodes, which
// would fight over the same state directory.
func (c *Config) StatusURL() string { return "http://" + c.Router.PACListen + "/status" }

// LocalHandler serves the PAC file and the daemon's local API on one
// loopback listener.
func (c *Config) LocalHandler(m *Manager) http.Handler {
	mux := http.NewServeMux()
	pac := func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/x-ns-proxy-autoconfig")
		w.Header().Set("Cache-Control", "no-store")
		fmt.Fprint(w, c.PAC())
	}
	mux.Handle("/proxy.pac", guard(pac, false))
	mux.Handle("/", guard(pac, false))
	mux.Handle("/status", guard(func(w http.ResponseWriter, r *http.Request) {
		ctx, cancel := context.WithTimeout(r.Context(), 10*time.Second)
		defer cancel()
		writeJSON(w, http.StatusOK, m.Status(ctx))
	}, false))
	mux.Handle("/shutdown", guard(func(w http.ResponseWriter, r *http.Request) {
		if !m.RequestStop() {
			writeJSON(w, http.StatusServiceUnavailable,
				map[string]string{"error": "this daemon cannot stop itself"})
			return
		}
		writeJSON(w, http.StatusOK, map[string]string{"status": "stopping"})
	}, true))
	mux.Handle("/prefs", guard(func(w http.ResponseWriter, r *http.Request) {
		var req PrefsRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
			return
		}
		st, err := m.SetPrefs(r.Context(), req.Profile, req.masked())
		reply(w, st, err)
	}, true))
	mux.Handle("/logout", guard(func(w http.ResponseWriter, r *http.Request) {
		var req PrefsRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
			return
		}
		st, err := m.Logout(r.Context(), req.Profile)
		reply(w, st, err)
	}, true))
	return mux
}

// PrefsRequest is the POST /prefs body: absent field means "leave alone".
type PrefsRequest struct {
	Profile          string  `json:"profile"`
	AcceptRoutes     *bool   `json:"accept_routes,omitempty"`
	AcceptDNS        *bool   `json:"accept_dns,omitempty"`
	ShieldsUp        *bool   `json:"shields_up,omitempty"`
	ExitNode         *string `json:"exit_node,omitempty"`
	ExitNodeAllowLAN *bool   `json:"exit_node_allow_lan,omitempty"`
}

func (r PrefsRequest) masked() *ipn.MaskedPrefs {
	mp := &ipn.MaskedPrefs{}
	if r.AcceptRoutes != nil {
		mp.RouteAll, mp.RouteAllSet = *r.AcceptRoutes, true
	}
	if r.AcceptDNS != nil {
		mp.CorpDNS, mp.CorpDNSSet = *r.AcceptDNS, true
	}
	if r.ShieldsUp != nil {
		mp.ShieldsUp, mp.ShieldsUpSet = *r.ShieldsUp, true
	}
	if r.ExitNode != nil {
		mp.ExitNodeID, mp.ExitNodeIDSet = tailcfg.StableNodeID(*r.ExitNode), true
	}
	if r.ExitNodeAllowLAN != nil {
		mp.ExitNodeAllowLANAccess, mp.ExitNodeAllowLANAccessSet = *r.ExitNodeAllowLAN, true
	}
	return mp
}

func reply(w http.ResponseWriter, st Status, err error) {
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, st)
}

func writeJSON(w http.ResponseWriter, code int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	w.WriteHeader(code)
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	enc.Encode(v)
}

// guard is the whole authorization story for this listener. A browser loads
// the PAC file from it, so loopback alone is not a boundary: any page could
// otherwise POST here. No token file — anything able to read a token could
// already rewrite config.yaml and the state dir, so it would buy nothing.
func guard(h http.HandlerFunc, write bool) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		host := r.Host
		if h, _, err := net.SplitHostPort(host); err == nil {
			host = h
		}
		switch strings.Trim(host, "[]") {
		case "127.0.0.1", "localhost", "::1": // DNS rebinding
		default:
			http.Error(w, "bad host", http.StatusForbidden)
			return
		}
		if r.Header.Get("Origin") != "" {
			http.Error(w, "cross-origin requests are not accepted", http.StatusForbidden)
			return
		}
		switch r.Header.Get("Sec-Fetch-Site") {
		case "", "same-origin":
		default:
			http.Error(w, "cross-site requests are not accepted", http.StatusForbidden)
			return
		}
		if write {
			if r.Method != http.MethodPost {
				http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
				return
			}
			// Requiring JSON forces a preflight we never answer.
			if ct, _, _ := strings.Cut(r.Header.Get("Content-Type"), ";"); strings.TrimSpace(ct) != "application/json" {
				http.Error(w, "content-type must be application/json", http.StatusUnsupportedMediaType)
				return
			}
		}
		h(w, r)
	})
}

// PostPrefs and PostLogout are the CLI's side of the daemon API: the GUI only
// ever shells out to tsmux, so this is the only HTTP client.
func (c *Config) PostPrefs(req PrefsRequest) (Status, error) { return c.post("/prefs", req) }

func (c *Config) PostLogout(profile string) (Status, error) {
	return c.post("/logout", PrefsRequest{Profile: profile})
}

// Shutdown asks a running daemon to exit, whoever started it.
func (c *Config) Shutdown() error {
	cl := &http.Client{Timeout: 3 * time.Second}
	req, err := http.NewRequest(http.MethodPost, "http://"+c.Router.PACListen+"/shutdown", nil)
	if err != nil {
		return err
	}
	resp, err := cl.Do(req)
	if err != nil {
		return fmt.Errorf("tsmux daemon is not running")
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("daemon refused to stop (%s)", resp.Status)
	}
	return nil
}

func (c *Config) post(path string, body any) (Status, error) {
	b, err := json.Marshal(body)
	if err != nil {
		return Status{}, err
	}
	cl := &http.Client{Timeout: 30 * time.Second}
	resp, err := cl.Post("http://"+c.Router.PACListen+path, "application/json", bytes.NewReader(b))
	if err != nil {
		return Status{}, errDaemonDown
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		var e struct {
			Error string `json:"error"`
		}
		json.NewDecoder(resp.Body).Decode(&e)
		if e.Error == "" {
			e.Error = resp.Status
		}
		return Status{}, fmt.Errorf("%s", e.Error)
	}
	var st Status
	return st, json.NewDecoder(resp.Body).Decode(&st)
}

var errDaemonDown = fmt.Errorf("tsmux daemon is not running (start it with `tsmux up`)")

// FetchStatus reads the running daemon's status, or reports that it is down.
func (c *Config) FetchStatus() ([]Status, error) {
	cl := &http.Client{Timeout: 3 * time.Second}
	resp, err := cl.Get(c.StatusURL())
	if err != nil {
		return nil, errDaemonDown
	}
	defer resp.Body.Close()
	var out []Status
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out, nil
}

// --- system proxy -----------------------------------------------------------

type proxyState struct {
	Service string `json:"service"`
	Enabled bool   `json:"enabled"`
	URL     string `json:"url"`
}

func (c *Config) statePath() string {
	return filepath.Join(c.Paths.StateDir, "sysproxy.json")
}

// ApplySystemProxy points every active network service at the tsmux PAC file,
// recording what was there before so Restore can put it back.
func (c *Config) ApplySystemProxy() error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("automatic system proxy is macOS-only; point your browser at %s manually", c.PACURL())
	}
	services, err := networkServices()
	if err != nil {
		return err
	}
	var saved []proxyState
	for _, s := range services {
		st := readAutoProxy(s)
		saved = append(saved, st)
		if err := run("networksetup", "-setautoproxyurl", s, c.PACURL()); err != nil {
			return fmt.Errorf("%s: %w", s, err)
		}
	}
	if err := os.MkdirAll(filepath.Dir(c.statePath()), 0o700); err != nil {
		return err
	}
	b, _ := json.MarshalIndent(saved, "", "  ")
	return os.WriteFile(c.statePath(), b, 0o600)
}

func (c *Config) RestoreSystemProxy() error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("system proxy is macOS-only")
	}
	b, err := os.ReadFile(c.statePath())
	if err != nil {
		return fmt.Errorf("no recorded system proxy state: %w", err)
	}
	var saved []proxyState
	if err := json.Unmarshal(b, &saved); err != nil {
		return err
	}
	for _, s := range saved {
		if s.Enabled && s.URL != "" {
			_ = run("networksetup", "-setautoproxyurl", s.Service, s.URL)
		} else {
			_ = run("networksetup", "-setautoproxyurl", s.Service, " ")
			_ = run("networksetup", "-setautoproxystate", s.Service, "off")
		}
	}
	return os.Remove(c.statePath())
}

func (c *Config) SystemProxyStatus() ([]proxyState, error) {
	if runtime.GOOS != "darwin" {
		return nil, fmt.Errorf("system proxy is macOS-only")
	}
	services, err := networkServices()
	if err != nil {
		return nil, err
	}
	out := make([]proxyState, 0, len(services))
	for _, s := range services {
		out = append(out, readAutoProxy(s))
	}
	return out, nil
}

func networkServices() ([]string, error) {
	out, err := exec.Command("networksetup", "-listallnetworkservices").Output()
	if err != nil {
		return nil, err
	}
	var svcs []string
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		// A leading '*' marks a disabled service; the first line is a preamble.
		if line == "" || strings.HasPrefix(line, "*") || strings.HasPrefix(line, "An asterisk") {
			continue
		}
		svcs = append(svcs, line)
	}
	return svcs, nil
}

func readAutoProxy(service string) proxyState {
	st := proxyState{Service: service}
	out, err := exec.Command("networksetup", "-getautoproxyurl", service).Output()
	if err != nil {
		return st
	}
	for _, line := range strings.Split(string(out), "\n") {
		k, v, ok := strings.Cut(line, ": ")
		if !ok {
			continue
		}
		switch strings.TrimSpace(k) {
		case "URL":
			st.URL = strings.TrimSpace(v)
		case "Enabled":
			st.Enabled = strings.TrimSpace(v) == "Yes"
		}
	}
	if st.URL == "(null)" {
		st.URL = ""
	}
	return st
}

func run(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
