package tsmux

import (
	"encoding/json"
	"fmt"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

// PAC renders a proxy auto-config that sends each tailnet's names to that
// profile's own proxy port. Browsers then reach every tailnet at once, with
// no system-wide interception of ordinary traffic.
func (c *Config) PAC() string {
	var b strings.Builder
	b.WriteString("// generated by tsmux -- do not edit\nfunction FindProxyForURL(url, host) {\n")
	b.WriteString("  host = host.toLowerCase();\n")
	b.WriteString("  if (host === \"localhost\" || shExpMatch(host, \"127.*\") || shExpMatch(host, \"*.local\")) return \"DIRECT\";\n")
	// PAC files are real JavaScript, so test for a literal address directly
	// rather than letting isInNet() trigger a DNS lookup on every domain.
	b.WriteString("  var tsmuxIsIP = /^[0-9]{1,3}(\\.[0-9]{1,3}){3}$/.test(host);\n")

	for _, p := range c.Ordered() {
		proxy := fmt.Sprintf("PROXY 127.0.0.1:%d; SOCKS5 127.0.0.1:%d", p.HTTPPort, p.SOCKSPort)
		for _, s := range p.Suffixes {
			apex := strings.TrimPrefix(s, ".")
			b.WriteString(fmt.Sprintf("  if (dnsDomainIs(host, %q) || host === %q) return %q; // %s\n",
				s, apex, proxy, p.Name))
		}
		for _, r := range p.IPRoutes {
			if ip, mask, ok := cidrToPAC(r); ok {
				b.WriteString(fmt.Sprintf("  if (tsmuxIsIP && isInNet(host, %q, %q)) return %q; // %s\n", ip, mask, proxy, p.Name))
			}
		}
		if p.MatchRoot {
			b.WriteString(fmt.Sprintf("  if (isPlainHostName(host)) return %q; // %s match_root\n", proxy, p.Name))
		}
	}
	b.WriteString("  return \"DIRECT\";\n}\n")
	return b.String()
}

func cidrToPAC(cidr string) (ip, mask string, ok bool) {
	_, n, err := net.ParseCIDR(cidr)
	if err != nil || n.IP.To4() == nil {
		return "", "", false
	}
	m := n.Mask
	return n.IP.String(), fmt.Sprintf("%d.%d.%d.%d", m[0], m[1], m[2], m[3]), true
}

func (c *Config) PACURL() string { return "http://" + c.Router.PACListen + "/proxy.pac" }

// StatusURL is the running daemon's JSON status. Clients (the menu bar app,
// `tsmux status`) read it instead of starting their own tsnet nodes, which
// would fight over the same state directory.
func (c *Config) StatusURL() string { return "http://" + c.Router.PACListen + "/status" }

// LocalHandler serves the PAC file and the daemon's status API on one
// loopback listener.
func (c *Config) LocalHandler(status func() any) http.Handler {
	mux := http.NewServeMux()
	pac := func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/x-ns-proxy-autoconfig")
		w.Header().Set("Cache-Control", "no-store")
		fmt.Fprint(w, c.PAC())
	}
	mux.HandleFunc("/proxy.pac", pac)
	mux.HandleFunc("/", pac)
	mux.HandleFunc("/status", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.Header().Set("Cache-Control", "no-store")
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		enc.Encode(status())
	})
	return mux
}

// FetchStatus reads the running daemon's status, or reports that it is down.
func (c *Config) FetchStatus() ([]Status, error) {
	cl := &http.Client{Timeout: 3 * time.Second}
	resp, err := cl.Get(c.StatusURL())
	if err != nil {
		return nil, fmt.Errorf("tsmux daemon is not running (start it with `tsmux up`)")
	}
	defer resp.Body.Close()
	var out []Status
	if err := json.NewDecoder(resp.Body).Decode(&out); err != nil {
		return nil, err
	}
	return out, nil
}

// --- system proxy -----------------------------------------------------------

type proxyState struct {
	Service string `json:"service"`
	Enabled bool   `json:"enabled"`
	URL     string `json:"url"`
}

func (c *Config) statePath() string {
	return filepath.Join(c.Paths.StateDir, "sysproxy.json")
}

// ApplySystemProxy points every active network service at the tsmux PAC file,
// recording what was there before so Restore can put it back.
func (c *Config) ApplySystemProxy() error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("automatic system proxy is macOS-only; point your browser at %s manually", c.PACURL())
	}
	services, err := networkServices()
	if err != nil {
		return err
	}
	var saved []proxyState
	for _, s := range services {
		st := readAutoProxy(s)
		saved = append(saved, st)
		if err := run("networksetup", "-setautoproxyurl", s, c.PACURL()); err != nil {
			return fmt.Errorf("%s: %w", s, err)
		}
	}
	if err := os.MkdirAll(filepath.Dir(c.statePath()), 0o700); err != nil {
		return err
	}
	b, _ := json.MarshalIndent(saved, "", "  ")
	return os.WriteFile(c.statePath(), b, 0o600)
}

func (c *Config) RestoreSystemProxy() error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("system proxy is macOS-only")
	}
	b, err := os.ReadFile(c.statePath())
	if err != nil {
		return fmt.Errorf("no recorded system proxy state: %w", err)
	}
	var saved []proxyState
	if err := json.Unmarshal(b, &saved); err != nil {
		return err
	}
	for _, s := range saved {
		if s.Enabled && s.URL != "" {
			_ = run("networksetup", "-setautoproxyurl", s.Service, s.URL)
		} else {
			_ = run("networksetup", "-setautoproxyurl", s.Service, " ")
			_ = run("networksetup", "-setautoproxystate", s.Service, "off")
		}
	}
	return os.Remove(c.statePath())
}

func (c *Config) SystemProxyStatus() ([]proxyState, error) {
	if runtime.GOOS != "darwin" {
		return nil, fmt.Errorf("system proxy is macOS-only")
	}
	services, err := networkServices()
	if err != nil {
		return nil, err
	}
	out := make([]proxyState, 0, len(services))
	for _, s := range services {
		out = append(out, readAutoProxy(s))
	}
	return out, nil
}

func networkServices() ([]string, error) {
	out, err := exec.Command("networksetup", "-listallnetworkservices").Output()
	if err != nil {
		return nil, err
	}
	var svcs []string
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		// A leading '*' marks a disabled service; the first line is a preamble.
		if line == "" || strings.HasPrefix(line, "*") || strings.HasPrefix(line, "An asterisk") {
			continue
		}
		svcs = append(svcs, line)
	}
	return svcs, nil
}

func readAutoProxy(service string) proxyState {
	st := proxyState{Service: service}
	out, err := exec.Command("networksetup", "-getautoproxyurl", service).Output()
	if err != nil {
		return st
	}
	for _, line := range strings.Split(string(out), "\n") {
		k, v, ok := strings.Cut(line, ": ")
		if !ok {
			continue
		}
		switch strings.TrimSpace(k) {
		case "URL":
			st.URL = strings.TrimSpace(v)
		case "Enabled":
			st.Enabled = strings.TrimSpace(v) == "Yes"
		}
	}
	if st.URL == "(null)" {
		st.URL = ""
	}
	return st
}

func run(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s: %s", err, strings.TrimSpace(string(out)))
	}
	return nil
}
